### ISSUE TITLE
Documentação incompleta e bug no código

### ISSUE THREAD

**Issue by All3yp** [tilucasoli/Terminal-ToDo#2]
Seria melhor se o README tivesse explicando como usar código, pois não ficou explicito. 
Quando tentamos abrir no Xcode, o código crashou. 

<img width="1280" alt="Captura de Tela 2020-04-02 às 16 33 05" src="https://user-images.githubusercontent.com/29764688/78293940-d824e300-74ff-11ea-9188-daea1fbafb60.png">

**Comment by tilucasoli** [comment]
Boa noite Alley.

Obrigado pela sugestão, Reconhecemos nossas falhas ao apresentar o Readme incompleto, já estamos trabalhando nisso. Quanto ao bug apresentado, provavelmente ocorreu um erro com as dependências durante o processo de build, se puder refazer o processo de build, o error deve ser resolvido.
Agradecemos sua colaboração.

by Jessica Guiot and Lucas Oliveira
